### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#14]
Question should be Learning Target

and all of them will be I can statements, so can I can automatically be there, and then teachers can type in the rest?

and then response choices should be 

Not Yet
With Help
On my own 

~~Also, can there be some kind of leading prompt? Like "Read the learning target for this lesson and then click on the option that best represents your ability to complete this task at this moment in time."~~

**Comment by HofmaDresu** [comment]
For the choices: Are these defaults that the teacher can change, or will they always be those 3?

**Comment by MrsThorpe** [comment]
It will always be those 3

**Comment by HofmaDresu** [comment]
I split the leading prompt out into a different issue
