### ISSUE TITLE
Leading prompt for students

### ISSUE THREAD

**Issue by HofmaDresu** [HofmaDresu/Understanding#16]
Also, can there be some kind of leading prompt? Like "Read the learning target for this lesson and then click on the option that best represents your ability to complete this task at this moment in time."

**Comment by HofmaDresu** [comment]
@MrsThorpe Should this be a popup after the student enters the Learning Target Code, or just text at the top of the screen above the Learning Target Text?

If a popup, should it appear every time or only the first time on the student's device?

**Comment by MrsThorpe** [comment]
I think it should appear everytime, but it can be a pop up or a part of the standard screen above the learning target. Here's a thought: could it be its own screen where student click on a button that says like OKAY in order to get to the screen with the learning target on it?

**Comment by HofmaDresu** [comment]
It can be a separate screen, though I'm generally against click-through screens like that. Just adds an extra action that annoys users (people tend to not like extra clicks)

**Comment by HofmaDresu** [comment]
What about a popup that appears after the student enters the learning target code. The popup has 2 buttons: "Ok" and "I understand, don't show again", or something like that
