### ISSUE TITLE
Scrolling L to R 

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#17]
Things aren't quite fitting on the screen and L to R scroll is not enabled? I am guessing when ready it will all fit.

**Comment by HofmaDresu** [comment]
Correct, I just haven't taken any time on that. If you point out which screens don't work for you, I can tweak them for now. However, we shouldn't do any major layout until the screen designs are ready

**Comment by HofmaDresu** [comment]
This is handled by several of the new UI tickets. Closing this as it's not needed
