### ISSUE TITLE
Student Screen

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#18]
[app.pdf](https://github.com/HofmaDresu/Understanding/files/1514423/app.pdf)

See attached visual concept for student screen; note change of selection options from multiple-choice style to buttons

**Comment by HofmaDresu** [comment]
This gives a decent start. Couple questions/comments:

1. When a student taps a choice, does that immediately save the choice and move the student back to their login screen?
2. It would be best to make your designs mirror the actual screen as it'll appear on the device. For example on the Student Answer screen: We need to add a navigation bar to the top of the screen . This will likely have a background color matching the intro screen, and will contain a 'back' arrow + the screen title (potentially "I CAN"). We'll also need a text color that shows up well on that minty color

**Comment by MrsThorpe** [comment]
I don't know why they would have to go back ever...can you think of a reason?

**Comment by MrsThorpe** [comment]
I think the student choice should remain on there, because they will change it as the lesson goes on without logging in again (hopefully)

**Comment by HofmaDresu** [comment]
Mostly it's a standard navigation scheme that the user will expect, though we don't _have_ to have it (although Android users can always go back). In theory the student could enter an incorrect (but valid) code and land on the wrong question. Then they'd want to go back and use the correct one

**Comment by HofmaDresu** [comment]
Actually: now that I see that "lands on incorrect screen" case: It might be good to show the teacher's name somewhere on the screen.....though it's enough of an edge case that i don't think it's strictly necessary

**Comment by MrsThorpe** [comment]
When I look at other similar things that I use for formative assessment, there's no failsafe for that, so I would wager that it's okay

**Comment by HofmaDresu** [comment]
Ok. No nav bar it is then :)

**Comment by HofmaDresu** [comment]
Are we saying that all Learning Targets will start with "I Can" (giving the teacher no choice when they're creating it), or are we just making the first 2 words of the LT bold and mint?

**Comment by MrsThorpe** [comment]
Yes, "I CAN" statements are a pretty big deal in education

**Comment by HofmaDresu** [comment]
Ok. I'll adjust that part of the LT creation screen as part of this. Right now it defaults to "I Can" but allows the teacher to change it
