### ISSUE TITLE
title screen 

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#19]
logo can standalone and then go into login screen, or login can be present below logo 
![intro](https://user-images.githubusercontent.com/33426466/33393032-cd8ac4a0-d50b-11e7-8e8b-00a48d9f9c31.png)
![learn with me_logo_192x192_white](https://user-images.githubusercontent.com/33426466/33393033-cd99c608-d50b-11e7-9e97-05ca878b7d0b.png)

**Comment by HofmaDresu** [comment]
This will work for the title scree, but I don't think it will work well for the launch icon (the one that you click to open the app). The white and the small detail likely won't come out well at the smaller size. I'll create it so we can see how well it works, but wanted to let you know just in case

**Comment by HofmaDresu** [comment]
Actually, even if it looks good we shouldn't use this for the launch icon. Apple's guidelines recommend against words:

Use words only when they’re essential or part of a logo. An app’s name appears below its icon on the Home screen. Don’t include nonessential words that repeat the name or tell people what to do with your app, like "Watch" or "Play." If your design includes any text, emphasize words that relate to the actual content your app offers.
https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/
