### ISSUE TITLE
logo for app selection button 

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#20]
Feedback me please. 
![l_logo_192x192](https://user-images.githubusercontent.com/33426466/33496115-f2fabf4c-d696-11e7-84c8-cef4e2a0e0b6.png)

**Comment by HofmaDresu** [comment]
Looks good! I'll add it to the next version (will probably show up tomorrow or sunday)

**Comment by HofmaDresu** [comment]
Seems to work well. I noticed the green on this is different from the splash screen in the other ticket, is that intentional (they both work, just covering bases)
