### ISSUE TITLE
Login screen 

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#25]
Is there a value to having the words student or teacher display somewhere here so they can see if they clicked incorrectly on accident? If yes, then that does require a back arrow, right?
![login](https://user-images.githubusercontent.com/33426466/33562922-8d54f504-d8e4-11e7-93f5-5493cc7c5d48.png)

**Comment by MrsThorpe** [comment]
also what information do they need to login with? modify as necessary.

**Comment by MrsThorpe** [comment]
also, sign up vs sign in
can they just sign in without singing up? 
that might be easier in the beginning. I don't care that they have to enter it everytime. 
It can just be a single use thing unless that's not best

**Comment by MrsThorpe** [comment]
In my mind there's not a username and password or a sign up...just a login with a code and they input their name, like Quizzizz...

**Comment by HofmaDresu** [comment]
Student and Teacher login should be viewed as completely separate screens and each have their own ticket:

* Teacher
** Email textbox
** Password textbox
** Login button
** Register button (to create an account if they don't already have one)
*** This should take the user to a new screen where they add any account info you want (email, password, name, etc)

* Student (students don't actually have an account, so this isn't really a login. It's the same fields as we currently have)
** Question Code
** Email
** First Name
** Last Name

**Comment by HofmaDresu** [comment]
I agree that students don't need to log in. Teachers need to if we want to let them do things like: See previous LTs/answers, create an LT from one of their previous ones. We can eventually add a 'remember me' button for teachers too, if we want, so they don't have to log in every time

**Comment by HofmaDresu** [comment]
I'd also recommend removing the logo on these screens, as it'll get harder to fit with the fields on smaller devices

**Comment by MrsThorpe** [comment]
Why do we need student emails again?

**Comment by HofmaDresu** [comment]
hmmm, we probably don't. I figured it was something guaranteed to be unique, but if it's not useful we can ignore it

**Comment by HofmaDresu** [comment]
This is now covered by #26 and #27, so closing this
