### ISSUE TITLE
Student login screen 

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#26]
omit email if that is an option 
![slogin](https://user-images.githubusercontent.com/33426466/33567863-8f913f7c-d8f2-11e7-8fa2-40c96b6681f2.png)

**Comment by MrsThorpe** [comment]
...will fix that font though.

**Comment by MrsThorpe** [comment]
It is DilemHandwritten Medium if that is helpful

**Comment by HofmaDresu** [comment]
Yep, i need to know what the font is (I'm no typophile :) ) And need a way to get the font files, as devices don't have many built-in

**Comment by MrsThorpe** [comment]
![welcome students teachers](https://user-images.githubusercontent.com/33426466/33569692-7a300b80-d8f8-11e7-9ae7-671b69a832b4.png)

logo font used at top only (for readability)

**Comment by MrsThorpe** [comment]
Also just keep using the same mint....ignore my mint-variation ;)

**Comment by HofmaDresu** [comment]
We should have a 'back' arrow on this screen in case someone clicks the wrong user type or is just exploring the app. They shouldn't have to close the app to change between Student and Teacher

**Comment by MrsThorpe** [comment]
Can you put a white back arrow where it makes sense or do you need me to add it and submit a new png

**Comment by HofmaDresu** [comment]
I can handle this one on my own, just wanted to run it by you first :)
