### ISSUE TITLE
Teacher Login/Register Screens

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#27]
![teacherscreens](https://user-images.githubusercontent.com/33426466/33569761-b4d0ab3c-d8f8-11e7-8bc8-6f7bbcc44538.png)

**Comment by MrsThorpe** [comment]
![welcome students teachers2](https://user-images.githubusercontent.com/33426466/33569779-c5e827c4-d8f8-11e7-9b8b-4f029a9997b3.png)

Again ignore the mint. It's an inDesign-Publisher issue.

**Comment by HofmaDresu** [comment]
Couple thoughts:

* I usually see screens like this just start on the Login form, since that's the most common use-case, with a button that switches to Register (similarly, Register has a button for Login)
* We should have a 'back' arrow at this point in case someone clicks the wrong user type or is just exploring the app. They shouldn't have to close the app to change between Student and Teacher

**Comment by MrsThorpe** [comment]
Whatever is standard is fine; that's your area of expertise! Can you conceptualize that or do you need more on my end?

**Comment by HofmaDresu** [comment]
It's better for you to do a new comp for this one. I could make something, but it probably wouldn't be what you want :)

**Comment by MrsThorpe** [comment]
Can you give me a better understanding of the path the screens should take and the suggestion you're proposing? Not sure I understand how to redesign.

**Comment by HofmaDresu** [comment]
Yeah, something like:

1. User clicks "Teacher"
2. User lands on "Teacher Login" screen which has the following:
2.1 Email text box
2.2 Password text box
2.3 Login button
2.4 Text saying something like "Don't have an account?"
2.5 Button for "Register
3 User clicks "Register"
4 User lands on "Teacher Registration" screen which has the following
4.1 Email text box
4.2 Password text box
4.3 Confirm Password text box
4.4 Register button
4.5 Text saying something like "Already have an account?"
4.6 Button for "Log in"

**Comment by HofmaDresu** [comment]
^^ is just a suggestion. If you like the flow you created better, we can definitely go with it

**Comment by HofmaDresu** [comment]
Reopening because I didn't apply the new font
