### ISSUE TITLE
Determine what devices LWM need to work on

### ISSUE THREAD

**Issue by HofmaDresu** [HofmaDresu/Understanding#31]
We need to list out what device types / operating systems this needs to work on. Here's what I remember you mentioning, let me know if anything should be added / removed:

iOS >= 10
iPhones
iPads

Android >= Lollipop
Phones
Tablets

**Comment by MrsThorpe** [comment]
Yep, that's it. Schools that are 1:1 use iPads or Chromebooks, so that's what would be needed past the phone extension.

**Comment by HofmaDresu** [comment]
Ok, so the iPad and Chomebook should be our primary target, with phones as a backup? And do you know what model(s) of chromebook? I don't know much about that so need to research and make sure what I'm building will work on them

**Comment by MrsThorpe** [comment]
Phones first for sure, then Chromebook, then IPad.
Our Chromebooks are Acer C740, but I know it varies statewide.

**Comment by HofmaDresu** [comment]
Cool. Do your chromebooks have access to the Google Play Store? And do you have one that you can install LWM from the testing site (I can give you the Android URL and such)?

**Comment by MrsThorpe** [comment]
Yes and Yes

**Comment by HofmaDresu** [comment]
Cool, just sent you an invite to the android testing group. I think all you'll have to do is visit that URL on the chromebook (or any other android device). I don't need to register anything on my end

**Comment by HofmaDresu** [comment]
Devices tracked in readme
