### ISSUE TITLE
Teacher work flow: Student forgot phone

### ISSUE THREAD

**Issue by HofmaDresu** [HofmaDresu/Understanding#32]
This doesn't affect the application itself, more just food for thought. What does a teacher do if a student forgot their phone or for some reason can't use it?

Feel free to close this at anytime. It popped into my head, so I figured I'd write it down

**Comment by MrsThorpe** [comment]
Same as student forgot textbook: student does not participate. 
If they're 1:1, they can use their device instead of their phone. Otherwise, they're just not counted for that lesson. But 29/30 or so still isn't bad.
