### ISSUE TITLE
Decide on "accent" color

### ISSUE THREAD

**Issue by HofmaDresu** [HofmaDresu/Understanding#34]
Android uses an "accent" color in many of its controls, so we need to define it. The color should be a complement to our main 'mint' color, preferably in Hex format (#FFFFFF = white, for example). The "OK" button in the attached dialog is one of the areas that the accent color is used:

![image](https://user-images.githubusercontent.com/735475/33863751-519c83aa-deb7-11e7-9002-4eab1482e47b.png)

**Comment by MrsThorpe** [comment]
#f88379 coral
