### ISSUE TITLE
Students at each level

### ISSUE THREAD

**Issue by MrsThorpe** [HofmaDresu/Understanding#48]
Can the part where teachers can see which student is at which level have a white background and look like a traditional drop down/scroll down menu, or would it be too confusing? It's a little hard to read on the mint. 

If it needs to stay mint, can we increase the text size?

**Comment by HofmaDresu** [comment]
It should probably stay mint, though we can experiment. I haven't gotten to that screen yet, so you're seeing the thrown together version right now. I'm going to close this for now, but keep it in mind when I work on #29. If that doesn't turn out how you like, we can make changes
